
package ConsomationReservation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceReservation", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceReservation {


    /**
     * 
     * @param arg0
     * @return
     *     returns ConsomationReservation.Reservation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDetailReservation", targetNamespace = "http://Service/", className = "ConsomationReservation.GetDetailReservation")
    @ResponseWrapper(localName = "getDetailReservationResponse", targetNamespace = "http://Service/", className = "ConsomationReservation.GetDetailReservationResponse")
    @Action(input = "http://Service/ServiceReservation/getDetailReservationRequest", output = "http://Service/ServiceReservation/getDetailReservationResponse")
    public Reservation getDetailReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "effectuerReservation", targetNamespace = "http://Service/", className = "ConsomationReservation.EffectuerReservation")
    @ResponseWrapper(localName = "effectuerReservationResponse", targetNamespace = "http://Service/", className = "ConsomationReservation.EffectuerReservationResponse")
    @Action(input = "http://Service/ServiceReservation/effectuerReservationRequest", output = "http://Service/ServiceReservation/effectuerReservationResponse")
    public String effectuerReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5);

}
